/**
 * Phase 10 — Automation Engine: pure workflow planning helpers.
 *
 * No Convex, no fetch — this module is unit-testable (Phase 14) and keeps
 * the runner action thin. Planning is deterministic; an optional AI assist
 * at the runner level can split the query into subqueries, but the pipeline
 * must run fully without it (§2: no mandatory dependency).
 */

/** The steps of the flagship "research and prepare a report" workflow. */
export const RESEARCH_REPORT_STEPS = [
  "Understand objective",
  "Multi-source search (Andromeda)",
  "Read top sources",
  "Synthesize with citations",
  "Independent verification",
  "Save report to knowledge",
] as const;

export type StepStatus = "pending" | "active" | "done" | "failed";

export type WfStep = {
  label: string;
  status: StepStatus;
  detail?: string;
};

/** Fresh initial step list for a run. */
export function freshSteps(): WfStep[] {
  return RESEARCH_REPORT_STEPS.map((label) => ({ label, status: "pending" as const }));
}

/**
 * Mark one step by index and return the SAME array (in-place) so runner
 * code can keep a single `steps` binding without rebinding hazards.
 */
export function setStep(
  steps: WfStep[],
  index: number,
  status: StepStatus,
  detail?: string,
): WfStep[] {
  const s = steps[index];
  if (s) {
    s.status = status;
    if (detail !== undefined) s.detail = detail;
    else delete s.detail;
  }
  return steps;
}

/** Human-readable stage string from a step list (first non-done). */
export function stageOf(steps: WfStep[]): string {
  const active = steps.find((s) => s.status === "active");
  if (active) return active.label;
  const firstPending = steps.find((s) => s.status === "pending");
  return firstPending ? firstPending.label : "Finishing";
}

/**
 * Cross-search deduplication (master plan §9): canonical/normalized URL
 * first, then same-domain title duplicates — without discarding genuinely
 * different evidence (short or generic titles are never title-dropped).
 */
export function dedupeCitations<
  T extends { title: string; url: string },
>(citations: T[]): T[] {
  const seenUrl = new Set<string>();
  const seenTitle = new Set<string>();
  const out: T[] = [];

  const normUrl = (u: string) =>
    u
      .trim()
      .toLowerCase()
      .replace(/^https?:\/\//, "")
      .replace(/^www\./, "")
      .replace(/\/+$/, "")
      .replace(/[?&]utm_[^&]*/g, "");

  const normTitle = (t: string) =>
    t
      .toLowerCase()
      .replace(/[^a-z0-9 ]/g, "")
      .replace(/\s+/g, " ")
      .trim();

  for (const c of citations) {
    const u = normUrl(c.url);
    const t = normTitle(c.title);
    if (u.length > 0 && seenUrl.has(u)) continue;
    const host = safeHost(c.url);
    // Title-only dedupe requires a substantial title AND the same host —
    // similar headlines on different sites are legitimately different
    // evidence (§9: don't blindly remove differing results).
    if (t.length >= 24 && host !== "unknown" && seenTitle.has(`${host}::${t}`)) continue;
    if (u.length > 0) seenUrl.add(u);
    if (t.length >= 24) seenTitle.add(`${host}::${t}`);
    out.push(c);
  }
  return out;
}

function safeHost(url: string): string {
  try {
    return new URL(url).hostname.replace(/^www\./, "");
  } catch {
    return "unknown";
  }
}

/** Compose the report deliverable body from the pipeline outputs. */
export function composeReport(
  objective: string,
  answer: string,
  footer: string,
  verification: { verdict: string; notes: string[] },
): string {
  const verdictLine =
    verification.verdict === "pass"
      ? "Verification: independent check found no material issues."
      : verification.verdict === "warnings"
        ? `Verification: independent check noted concerns — ${verification.notes.join("; ")}`
        : verification.verdict === "failed"
          ? `Verification: independent check found problems — ${verification.notes.join("; ")}`
          : "Verification: not independently verified (no AI checker available).";
  return [
    `# Omi Research Report`,
    ``,
    `**Objective:** ${objective}`,
    ``,
    answer,
    ``,
    `---`,
    footer,
    ``,
    `---`,
    verdictLine,
    ``,
    `_Generated by the Omi Automation Engine (Ominnovations Intelligence). Sources were retrieved by Andromeda and every claim above traces to the numbered citations._`,
  ].join("\n");
}
